### ISSUE TITLE
visualisieren

### ISSUE THREAD

**Issue by ynux** [muc-fluechtlingsrat/bamf-asylgeschaeftsstatistik#2]

**Comment by kjc66** [comment]
[tabula-201603-statistik-anlage-asyl-geschaeftsbericht.xlsx](https://github.com/muc-fluechtlingsrat/bamf-asylgeschaeftsstatistik/files/253492/tabula-201603-statistik-anlage-asyl-geschaeftsbericht.xlsx)

**Comment by kjc66** [comment]
Visualisierung bereinigte versus unbereinigte Schutzquote, Excel-Datei generiert aus csv der BAMF-Asylgeschaeftsstatistik Maerz 2016.
